// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbmsg.proto

package netya

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PbMsg struct {
	Length               int32    `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Value0               int32    `protobuf:"varint,4,opt,name=Value0,proto3" json:"Value0,omitempty"`
	Value1               int32    `protobuf:"varint,5,opt,name=Value1,proto3" json:"Value1,omitempty"`
	Value2               int32    `protobuf:"varint,6,opt,name=Value2,proto3" json:"Value2,omitempty"`
	Payload              []byte   `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbMsg) Reset()         { *m = PbMsg{} }
func (m *PbMsg) String() string { return proto.CompactTextString(m) }
func (*PbMsg) ProtoMessage()    {}
func (*PbMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_27d5866e3399cd9e, []int{0}
}

func (m *PbMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbMsg.Unmarshal(m, b)
}
func (m *PbMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbMsg.Marshal(b, m, deterministic)
}
func (m *PbMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbMsg.Merge(m, src)
}
func (m *PbMsg) XXX_Size() int {
	return xxx_messageInfo_PbMsg.Size(m)
}
func (m *PbMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PbMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PbMsg proto.InternalMessageInfo

func (m *PbMsg) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *PbMsg) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PbMsg) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PbMsg) GetValue0() int32 {
	if m != nil {
		return m.Value0
	}
	return 0
}

func (m *PbMsg) GetValue1() int32 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *PbMsg) GetValue2() int32 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *PbMsg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*PbMsg)(nil), "netya.PbMsg")
}

func init() { proto.RegisterFile("pbmsg.proto", fileDescriptor_27d5866e3399cd9e) }

var fileDescriptor_27d5866e3399cd9e = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x48, 0xca, 0x2d,
	0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0x4b, 0x2d, 0xa9, 0x4c, 0x54, 0x5a,
	0xcb, 0xc8, 0xc5, 0x1a, 0x90, 0xe4, 0x5b, 0x9c, 0x2e, 0x24, 0xc6, 0xc5, 0x96, 0x93, 0x9a, 0x97,
	0x5e, 0x92, 0x21, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe5, 0x09, 0x09, 0x71, 0xb1, 0x24,
	0xe7, 0xa7, 0xa4, 0x4a, 0x30, 0x81, 0x45, 0xc1, 0x6c, 0x90, 0xda, 0xd2, 0xe2, 0xd4, 0x22, 0xcf,
	0x14, 0x09, 0x66, 0x88, 0x5a, 0x08, 0x0f, 0x24, 0x1e, 0x96, 0x98, 0x53, 0x9a, 0x6a, 0x20, 0xc1,
	0x02, 0x11, 0x87, 0xf0, 0xe0, 0xe2, 0x86, 0x12, 0xac, 0x48, 0xe2, 0x86, 0x70, 0x71, 0x23, 0x09,
	0x36, 0x24, 0x71, 0x23, 0x21, 0x09, 0x2e, 0xf6, 0x82, 0xc4, 0xca, 0x9c, 0xfc, 0xc4, 0x14, 0x09,
	0x76, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x18, 0x37, 0x89, 0x0d, 0xec, 0x7a, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x94, 0xa5, 0x15, 0x72, 0xcc, 0x00, 0x00, 0x00,
}
