// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbmsg.proto

package netya

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Msg struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Value0               int32    `protobuf:"varint,3,opt,name=Value0,proto3" json:"Value0,omitempty"`
	Value1               int32    `protobuf:"varint,4,opt,name=Value1,proto3" json:"Value1,omitempty"`
	Value2               int32    `protobuf:"varint,5,opt,name=Value2,proto3" json:"Value2,omitempty"`
	Payload              []byte   `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_27d5866e3399cd9e, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Msg) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Msg) GetValue0() int32 {
	if m != nil {
		return m.Value0
	}
	return 0
}

func (m *Msg) GetValue1() int32 {
	if m != nil {
		return m.Value1
	}
	return 0
}

func (m *Msg) GetValue2() int32 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func (m *Msg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Msg)(nil), "netya.Msg")
}

func init() { proto.RegisterFile("pbmsg.proto", fileDescriptor_27d5866e3399cd9e) }

var fileDescriptor_27d5866e3399cd9e = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x48, 0xca, 0x2d,
	0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0x4b, 0x2d, 0xa9, 0x4c, 0x54, 0x9a,
	0xcc, 0xc8, 0xc5, 0xec, 0x5b, 0x9c, 0x2e, 0x24, 0xc4, 0xc5, 0x92, 0x9c, 0x9f, 0x92, 0x2a, 0xc1,
	0xa8, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0x66, 0x0b, 0x89, 0x71, 0xb1, 0x95, 0x16, 0xa7, 0x16, 0x79,
	0xa6, 0x48, 0x30, 0x81, 0x45, 0xa1, 0x3c, 0x90, 0x78, 0x58, 0x62, 0x4e, 0x69, 0xaa, 0x81, 0x04,
	0x33, 0x44, 0x1c, 0xc2, 0x83, 0x8b, 0x1b, 0x4a, 0xb0, 0x20, 0x89, 0x1b, 0xc2, 0xc5, 0x8d, 0x24,
	0x58, 0x91, 0xc4, 0x8d, 0x84, 0x24, 0xb8, 0xd8, 0x0b, 0x12, 0x2b, 0x73, 0xf2, 0x13, 0x53, 0x24,
	0xd8, 0x14, 0x18, 0x35, 0x78, 0x82, 0x60, 0xdc, 0x24, 0x36, 0xb0, 0x1b, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x7f, 0x10, 0x50, 0x18, 0xb2, 0x00, 0x00, 0x00,
}
