// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RpcCall struct {
	Seq                  int64    `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ServiceName          string   `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Req                  []byte   `protobuf:"bytes,3,opt,name=req,proto3" json:"req,omitempty"`
	Resp                 []byte   `protobuf:"bytes,4,opt,name=resp,proto3" json:"resp,omitempty"`
	Err                  string   `protobuf:"bytes,5,opt,name=err,proto3" json:"err,omitempty"`
	Reply                bool     `protobuf:"varint,6,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcCall) Reset()         { *m = RpcCall{} }
func (m *RpcCall) String() string { return proto.CompactTextString(m) }
func (*RpcCall) ProtoMessage()    {}
func (*RpcCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *RpcCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcCall.Unmarshal(m, b)
}
func (m *RpcCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcCall.Marshal(b, m, deterministic)
}
func (m *RpcCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcCall.Merge(m, src)
}
func (m *RpcCall) XXX_Size() int {
	return xxx_messageInfo_RpcCall.Size(m)
}
func (m *RpcCall) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcCall.DiscardUnknown(m)
}

var xxx_messageInfo_RpcCall proto.InternalMessageInfo

func (m *RpcCall) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *RpcCall) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *RpcCall) GetReq() []byte {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *RpcCall) GetResp() []byte {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (m *RpcCall) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *RpcCall) GetReply() bool {
	if m != nil {
		return m.Reply
	}
	return false
}

func init() {
	proto.RegisterType((*RpcCall)(nil), "rpc.RpcCall")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xce, 0xb1, 0x0a, 0x02, 0x31,
	0x0c, 0x06, 0x60, 0x62, 0xef, 0x4e, 0x2f, 0x3a, 0x48, 0x70, 0xc8, 0x58, 0x9c, 0x3a, 0xb9, 0xf8,
	0x08, 0xee, 0x0e, 0x7d, 0x83, 0xb3, 0x64, 0x10, 0x2a, 0x97, 0x4b, 0x45, 0xf0, 0x19, 0x7c, 0x69,
	0x69, 0x5d, 0xdc, 0xbe, 0xfc, 0xe4, 0x87, 0x1f, 0x47, 0xd3, 0x74, 0x52, 0x9b, 0x9f, 0x33, 0x39,
	0xd3, 0x74, 0xfc, 0x00, 0xae, 0xa3, 0xa6, 0xcb, 0x94, 0x33, 0xed, 0xd1, 0x15, 0x59, 0x18, 0x3c,
	0x04, 0x17, 0x2b, 0xc9, 0xe3, 0xb6, 0x88, 0xbd, 0xee, 0x49, 0xae, 0xd3, 0x43, 0x78, 0xe5, 0x21,
	0x8c, 0xf1, 0x3f, 0xaa, 0x1d, 0x93, 0x85, 0x9d, 0x87, 0xb0, 0x8b, 0x95, 0x44, 0xd8, 0x99, 0x14,
	0xe5, 0xae, 0x45, 0xcd, 0xf5, 0x4b, 0xcc, 0xb8, 0x6f, 0xfd, 0x4a, 0x3a, 0x60, 0x6f, 0xa2, 0xf9,
	0xcd, 0x83, 0x87, 0xb0, 0x89, 0xbf, 0xe3, 0x36, 0xb4, 0x65, 0xe7, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x1d, 0x61, 0xb4, 0x3b, 0xa6, 0x00, 0x00, 0x00,
}
